services:

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9412:9411"
    networks:
      - dapr-network

  dapr-dashboard:
    image: "daprio/dashboard:latest"
    command: [ "--docker-compose=true", 
      "--components-path=/home/nonroot/components", 
      "--config-path=/home/nonroot/configuration", 
      "--docker-compose-path=/home/nonroot/docker-compose.yml" ]
    ports:
      - "8090:8080"
    volumes:
      - "./components/:/home/nonroot/components"
      - "./configuration/:/home/nonroot/configuration"
      - ./docker-compose.yml:/home/nonroot/docker-compose.yml
    networks:
      - my-network

  apidapr2:
    image: ${DOCKER_REGISTRY-}apidapr2
    build:
      context: .
      dockerfile: apidapr2/Dockerfile
    networks:
      - dapr-network

  apidapr2-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apidapr2",
     "-app-port", "8080",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - apidapr2
    network_mode: "service:apidapr2"

  apidapr1:
    image: ${DOCKER_REGISTRY-}apidapr1
    build:
      context: .
      dockerfile: apidapr1/Dockerfile
    networks:
      - dapr-network

  apidapr1-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "apidapr1",
     "-app-port", "8083",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50002",
     "-components-path", "/components"]
    volumes:
        - "./components/:/components"
        - "./configuration/:/configuration"
    depends_on:
      - apidapr1
    network_mode: "service:apidapr1"

 ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - dapr-network
networks:
    dapr-network: